# Generated by Django 2.2.11 on 2020-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_admin_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver', models.CharField(default='', max_length=30)),
                ('message', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
