# Generated by Django 2.2.11 on 2020-04-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_adminmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessage',
            old_name='reciver',
            new_name='selReciver',
        ),
    ]
