# Generated by Django 2.2.11 on 2020-04-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200402_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='noSem',
            field=models.IntegerField(default=''),
        ),
    ]
