# Generated by Django 2.2.11 on 2020-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200404_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='studentid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
