# Generated by Django 2.2.11 on 2020-04-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_studentdetail_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='courseId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
