# Generated by Django 2.2.11 on 2020-04-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_studentdetail_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default='', max_length=50)),
                ('semister', models.CharField(default='', max_length=50)),
                ('subjectcode1', models.CharField(default='', max_length=50)),
                ('subject1', models.CharField(default='', max_length=50)),
                ('subjectcode2', models.CharField(default='', max_length=50)),
                ('subject2', models.CharField(default='', max_length=50)),
                ('subjectcode3', models.CharField(default='', max_length=50)),
                ('subject3', models.CharField(default='', max_length=50)),
                ('subjectcode4', models.CharField(default='', max_length=50)),
                ('subject4', models.CharField(default='', max_length=50)),
                ('subjectcode5', models.CharField(default='', max_length=50)),
                ('subject5', models.CharField(default='', max_length=50)),
                ('subjectcode6', models.CharField(default='', max_length=50)),
                ('subject6', models.CharField(default='', max_length=50)),
                ('subjectcode7', models.CharField(default='', max_length=50)),
                ('subject7', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
